# Generated by Django 6.0.5 on 2026-06-06 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=120, verbose_name='نام')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('guest_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='موضوع')),
                ('source', models.CharField(choices=[('widget', 'ویجت پشتیبانی'), ('contact', 'فرم تماس')], default='widget', max_length=20, verbose_name='منبع')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته')], default='open', max_length=20, verbose_name='وضعیت')),
                ('staff_unread_count', models.PositiveIntegerField(default=0, verbose_name='پیام\u200cهای خوانده\u200cنشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گفتگوی پشتیبانی',
                'verbose_name_plural': 'گفتگوهای پشتیبانی',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False, verbose_name='پاسخ پشتیبانی')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_chat.supportthread', verbose_name='گفتگو')),
            ],
            options={
                'verbose_name': 'پیام پشتیبانی',
                'verbose_name_plural': 'پیام\u200cهای پشتیبانی',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='supportthread',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'widget'), ('user__isnull', False)), fields=('user',), name='unique_widget_thread_per_user'),
        ),
    ]
