# Generated by Django 6.0.5 on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="authority",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="شناسه جلسه پرداخت آنلاین (مثلاً زرین‌پال)",
                max_length=100,
                verbose_name="کد authority درگاه",
            ),
        ),
        migrations.AlterField(
            model_name="wallettransaction",
            name="reference_code",
            field=models.CharField(
                blank=True,
                help_text="کد پیگیری درگاه پس از پرداخت موفق",
                max_length=64,
                verbose_name="کد پیگیری",
            ),
        ),
    ]
