# Generated by Django 6.0.5 on 2026-06-06 12:24

import app_content.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دوره')),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True, verbose_name='نامک')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('instructor_name', models.CharField(default='تیم آموزش', max_length=120, verbose_name='مدرس')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=app_content.models.course_thumbnail_upload_to, verbose_name='تصویر')),
                ('level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=20, verbose_name='سطح')),
                ('is_free', models.BooleanField(default=False, verbose_name='رایگان')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت (تومان)')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True, verbose_name='نامک')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=app_content.models.tutorial_thumbnail_upload_to, verbose_name='تصویر')),
                ('video_url', models.URLField(help_text='آپارات، CDN یا فایل استاتیک', verbose_name='لینک ویدیو')),
                ('duration_minutes', models.PositiveIntegerField(default=10, verbose_name='مدت (دقیقه)')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'آموزش',
                'verbose_name_plural': 'آموزش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True, verbose_name='نامک')),
                ('excerpt', models.TextField(blank=True, verbose_name='خلاصه')),
                ('body', models.TextField(verbose_name='متن')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=app_content.models.blog_thumbnail_upload_to, verbose_name='تصویر شاخص')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app_content.blogcomment', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_content.blogpost', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'نظر بلاگ',
                'verbose_name_plural': 'نظرات بلاگ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان جلسه')),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, verbose_name='نامک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('video_url', models.URLField(verbose_name='لینک ویدیو')),
                ('duration_minutes', models.PositiveIntegerField(default=10, verbose_name='مدت (دقیقه)')),
                ('is_preview', models.BooleanField(default=False, verbose_name='پیش\u200cنمایش رایگان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='app_content.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'جلسه دوره',
                'verbose_name_plural': 'جلسات دوره',
                'ordering': ['order', 'id'],
                'unique_together': {('course', 'slug')},
            },
        ),
    ]
