# Generated by Django 6.0.5 on 2026-06-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_content", "0002_alter_blogcomment_is_approved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "۱ ستاره"), (2, "۲ ستاره"), (3, "۳ ستاره"), (4, "۴ ستاره"), (5, "۵ ستاره")],
                        verbose_name="امتیاز",
                    ),
                ),
                ("text", models.TextField(verbose_name="نظر")),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="نظر پس از تایید در سایت نمایش داده می‌شود",
                        verbose_name="تایید شده",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="app_content.course",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر دوره",
                "verbose_name_plural": "نظرات دوره",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="coursereview",
            constraint=models.UniqueConstraint(fields=("course", "user"), name="uniq_course_review_user"),
        ),
    ]
