# Generated by Django 6.0.5 on 2026-06-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_content", "0003_coursereview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEnrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price_paid", models.PositiveIntegerField(default=0, verbose_name="مبلغ پرداخت‌شده (تومان)")),
                ("enrolled_at", models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="app_content.course",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_enrollments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "ثبت‌نام دوره",
                "verbose_name_plural": "ثبت‌نام‌های دوره",
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="courseenrollment",
            constraint=models.UniqueConstraint(fields=("user", "course"), name="uniq_course_enrollment_user"),
        ),
    ]
