# Generated by Django 6.0.5 on 2026-06-06 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0004_courseenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='کد authority درگاه')),
                ('reference_code', models.CharField(blank=True, max_length=64, verbose_name='کد پیگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='app_content.course', verbose_name='دوره')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='app_content.courseenrollment', verbose_name='ثبت\u200cنام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_purchases', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'خرید دوره',
                'verbose_name_plural': 'خریدهای دوره',
                'ordering': ['-created_at'],
            },
        ),
    ]
